<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../CoreLib/CoreLib.csproj" />
    <ProjectReference Include="../TaskService.DAL/TaskService.DAL.csproj" />
  </ItemGroup>
</Project>